### ISSUE TITLE
BJ-Share not working anymore 

### ISSUE THREAD

**Issue by VozDeOuro** [Prowlarr/Indexers#159] opened 2022-03-30 02:49 UTC
when we test the tracker 
![image](https://user-images.githubusercontent.com/36045463/160740781-253d8993-c7d1-4578-b6f4-34429a427112.png)

it shows that is working but when we try to download some content we get a red cloud
![image](https://user-images.githubusercontent.com/36045463/160741052-8cb7d0ef-c172-412c-b879-f438fb229c4d.png)

[AB#2885](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2885)

**Comment by bakerboy448** [comment] 2022-03-30 02:55
Closing; invalid issue; no template, not a bug report.




Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

**Closed** 2022-03-30 02:55 UTC
