### ISSUE TITLE
Indexer "cpasbien" broken due to false url

### ISSUE THREAD

**Issue by Jexx33** [Prowlarr/Indexers#300] opened 2023-01-19 16:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Indexer "cpasbien" no longer work. The url in parameters is totally bullshit and was not here previously.

### Expected Behavior

restore the url https://www.cpasbien.si

Maybe a way for the user to set a custom url or add one in the list

### Environment

```markdown
- OS: OMV
- Prowlarr: 1.1.0.2322
- Docker Install: yes
- Using Reverse Proxy: i think not
- Browser: Firefox 108.0.2
```

### What branch are you running?

Master

### Trace Logs?

![image](https://user-images.githubusercontent.com/110617560/213506140-e79e8bd5-0066-40f2-ab86-cc8ca3ff1a0b.png)

[AB#4763](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4763)

[AB#4764](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4764)

**Comment by bakerboy448** [comment] 2023-01-19 17:36
https://github.com/Jackett/Jackett/commit/c70e8bb189b17ede3226050c2317d7edc828e313
@garfield69 another domain change for cpasbien?

**Comment by garfield69** [comment] 2023-01-19 18:12
cpasbien.si its a different site with a different engine.
httpGET: https://www.cpasbien.si/recherche/bad%20batch
httpPOST: https://labastidevivante.fr/index.php?do=search&subaction=search payload: story=bad+batch

the previous domain https://cpasbiens3.fr/ redirects to https://labastidevivante.fr/ so that is apparently legit.

on jackett we have a second cpasbien indexer, cpasbienclone that is on https://www.cpasbien.tw/ that uses a different search engine
httpGET: https://www.cpasbien.tw/search_torrent/bad%20batch.html

do we want to add cpasbien.si as a third indexer?

**Comment by garfield69** [comment] 2023-01-19 18:46
https://github.com/Jackett/Jackett/issues/13919 https://github.com/Jackett/Jackett/commit/a6a9fb73e952488faffbc97b7ed82d015db175d7

**Comment by Jexx33** [comment] 2023-01-19 19:41
https://gist.github.com/Jexx33/6c4c5756ff74154877b235e328f59fcc

**Comment by bakerboy448** [comment] 2023-01-19 20:37
```
2023-01-19 20:33:42.1|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.1.105:8191/v1: 500.InternalServerError (259 bytes)
{"status": "error", "message": "Error: Error solving the challenge. Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.", "startTimestamp": 1674156809428, "endTimestamp": 1674156822191, "version": "3.0.2"}
```

Closing / No action needed; not a bug.

**Closed by bakerboy448** 2023-01-19 20:37 UTC
Labels: Type: Bug

**Comment by Jexx33** [comment] 2023-01-19 20:45
What can i do to make it fonctional?

**Comment by bakerboy448** [comment] 2023-01-20 01:00
That's a question for the site as it appears their cloudflare rules have blocked your IP. Nothing to do with prowlarr

**Comment by Jexx33** [comment] 2023-01-20 16:08
Thanks i will check my vpn and flaresolverr
