### ISSUE TITLE
Error [Warn] Cardigann: Invalid Release: 'XXXXXX' from indexer: SceneRush. No categories provided.

### ISSUE THREAD

**Issue by dabasiu** [Prowlarr/Indexers#497] opened 2024-11-12 16:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

searching for movies or tv-series on the indexer SceneRush gives the error No categories provided. I can reproduce the error from the GUI (attach a screenshot) - The filter for categories is working but the results is not processed correctly
![image](https://github.com/user-attachments/assets/0c76f8e4-f83d-46c6-8873-8a6ec2d5330e)

### Expected Behavior

The category on the results have the right category instead of unknown

### Steps To Reproduce

from the web UI, make any search for index SceneRush and Categories Movies and/or TV.. The results will have unknown category

### Environment

```markdown
- OS: Unraid 6.12.6
- Prowlarr:1.25.4.4818
- Docker Install:yes
- Using Reverse Proxy:no
- Browser:not related with UI
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr-logs.txt](https://github.com/user-attachments/files/17720096/prowlarr-logs.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by dabasiu** [comment] 2024-11-15 14:10
thanks for the reply. Someone with an account on the tracker? That category mapping in the YAML definition is on tracker integration with prowlarr? I contact the staff of the tracker.. Waiting to see what they tell..

**Comment by TiagoJVO** [comment] 2024-11-15 23:54
Hi team! I was looking to setup this index and stumbled across this thread.
Seems the problem is that the provider changed the categories.
For example, I see that in the code for 4k movies the index is expecting `div.cat-4k`: https://github.com/Prowlarr/Indexers/blob/df6238b386070b9038801fe7e070d1714204326e/definitions/v10/scenerush.yml#L128 
and the category is now `cat-filme-4k`.

I'll try to do a PR with the new mapping.

**Comment by bakerboy448** [comment] 2024-11-15 23:59
PR to jackett please and then we'll pull it downstream

**Comment by TiagoJVO** [comment] 2024-11-16 02:13
> PR to jackett please and then we'll pull it downstream

It is merged now, what is the process to pull?

**Comment by TiagoJVO** [comment] 2024-11-16 02:13
> PR to jackett please and then we'll pull it downstream

It is merged now @bakerboy448, what is the process to pull?

**Comment by bakerboy448** [comment] 2024-11-16 02:17
https://github.com/Prowlarr/Indexers/commit/a38af61d0ea925c5128a74d2e5d5c3f378566c71
preciate the ping

**Closed by bakerboy448** 2024-11-16 02:17 UTC
Labels: Type: Bug, Status: Help Wanted, Status: Needs Triage

**Comment by dabasiu** [comment] 2024-11-19 17:55
thank you all
