### ISSUE TITLE
Prowlarr incorrectly parsing added date from TorrentLeech

### ISSUE THREAD

**Issue by azkar0** [Prowlarr/Indexers#280] opened 2022-12-03 21:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

This appears like it's the same issue as https://github.com/Prowlarr/Prowlarr/issues/720, which was closed as fixed, but I'm still seeing this behaviour.

When a search is performed in Prowlarr (or through the *arr apps), Prowlarr appears to be dropping the _date_ that TorrentLeech reports, instead interpreting it as today's date. This results in a large number of results with a negative age.

Entry on TL:
![image](https://user-images.githubusercontent.com/119238655/205463190-f06dd934-8ada-4fe5-b2a1-245772786a79.png)

Data returned by TL during the Prowlarr search:
{"fid":"240934320","filename":"The.Simpsons.S34E07.XviD-AFG.torrent","name":"The Simpsons S34E07 XviD-AFG","**addedTimestamp":"2022-11-13 23:02:08**","categoryID":26,"size":293497266,"completed":44,"seeders":19,"leechers":0,"numComments":0,"tags":["comedy","Family"],"new":false,"imdbID":"","rating":0,"genres":"","tvmazeID":"e2415696","igdbID":"","download_multiplier":1}

Result in Prowlarr:
![image](https://user-images.githubusercontent.com/119238655/205463248-1f38bf78-e7b1-4f0c-9b69-20740d8b29e8.png)

It seems some of the results show the correct added date/age in Prowlarr, but I can't figure out any rhyme or reason to which do and which don't.

### Expected Behavior

Use the date returned by TorrentLeech, not today's date.

### Steps To Reproduce

Perform any search in Prowlarr, and look at the age of results returned from TorrentLeech.

### Environment

```markdown
- OS: Windows 11
- Prowlarr:0.4.9.2083
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome 107.0.5304.122
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/azkar0/53e9aa928f41a7016efa69cba934f46b

[AB#4288](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4288)

[AB#4439](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4439)

**Comment by bakerboy448** [comment] 2022-12-12 17:26
@ilike2burnthing any insight here?

**Comment by bakerboy448** [comment] 2022-12-12 17:26
@ilike2burnthing any insight here?

**Comment by ilike2burnthing** [comment] 2022-12-12 22:05
I think it may be related to https://github.com/Jackett/Jackett/commit/05fb6b36a0760cea4444f78ca709a08d254e1811

Unfortunately, I'm poorly placed to test this (GMT). @garfield69 are you seeing the same issue with TorrentLeech as with the unit3d JSON indexers?

**Comment by bakerboy448** [comment] 2022-12-15 20:25
@azkar0 

does your timezone on configured in torrentleech match your system's timezone?

**Comment by azkar0** [comment] 2022-12-16 02:38
The timezone set on TL matches my system timezone.

**Comment by garfield69** [comment] 2022-12-17 22:31
@azkar0 FWIW, if you want more confidence that the issue is with Prowlarr, then I suggest you try using Jackett as a control.
if the jackett torrentleech indexer correctly shows your the date/time compare to their website, then you know its a problem with Prowlarr.
If however Jackett shows the same time offset as Prowlarr then clearly something will be amiss with your setup because other Jackett users are not having this issue with this indexer.

**Comment by Qstick** [comment] 2022-12-18 20:57
This is likely fixed in latest

**Closed** 2022-12-21 03:11 UTC
Labels: Type: Bug, Status: Needs Triage
